In [4]:
import numpy as np

a=[1,2,3,4]
b=np.array(a)
print(b, type(b))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [8]:
b=np.zeros((3,4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
b=np.ones(3)
b

array([1., 1., 1.])

In [11]:
b=np.full((2,3),6)
b

array([[6, 6, 6],
       [6, 6, 6]])

In [29]:
b=np.empty(4)
b

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [28]:
b=np.empty(4, dtype=int)
b

array([1, 2, 3, 4])

In [30]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b=np.zeros(10,dtype=int)
b[4]=1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [34]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
b=np.arange(3,10,2)
b

array([3, 5, 7, 9])

In [37]:
b=np.linspace(3,10)
b

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [42]:
b=np.linspace(3,10)
print(b[1]-b[0])
print(b[2]-b[1])

0.1428571428571428
0.1428571428571428


In [39]:
b=np.linspace(3,10,6,dtype=int)
b

array([ 3,  4,  5,  7,  8, 10])

In [43]:
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
b=np.eye(5,6,dtype=int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [49]:
b=np.random.rand(3)
b

array([0.28367456, 0.2412862 , 0.10992485])

In [51]:
b=np.random.rand(2,3)*10
b

array([[9.16487117, 4.18284058, 6.54746428],
       [0.87852576, 7.15535855, 7.18669875]])

In [69]:
b=np.random.randint(3,10)
b

6

In [74]:
b=np.random.randint(10,size=(10))
b

array([4, 6, 5, 2, 5, 6, 1, 3, 8, 7])

In [75]:
b=np.random.randint(10, size=(4,4))
b

array([[6, 7, 9, 8],
       [8, 6, 6, 6],
       [8, 7, 9, 8],
       [9, 9, 9, 6]])

In [77]:
b=np.arange(9,50)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [85]:
b=np.linspace(0,5,9).round(2)
b

array([0.  , 0.62, 1.25, 1.88, 2.5 , 3.12, 3.75, 4.38, 5.  ])

In [92]:
import numpy as np
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [91]:
print(li_2d[1][:3])
print(arr_2d[1][:3])

[5, 6, 7]
[5 6 7]


In [96]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [97]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [95]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [100]:
print(li_2d[2:4][1:3])
print(arr_2d[2:4,1:3])

[[13, 14, 15, 16]]
[[10 11]
 [14 15]]


In [102]:
arr_2d_copr = arr_2d.copy()

In [103]:
print(arr_2d)
print(arr_2d_copr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [104]:
c = arr_2d + 1
c

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [105]:
c = arr_2d + arr_2d_copr
c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [106]:
c = c - arr_2d_copr
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
c = arr_2d * arr_2d_copr
c

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [108]:
c = c/arr_2d
c

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [110]:
c = c//arr_2d
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
print(arr_2d)
print(arr_2d_copr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [119]:
print(arr_2d.max())
print("Index: ", arr_2d.argmax())
print(arr_2d.min())
print("Index: ",arr_2d.argmin())
print(arr_2d.sum())
print(arr_2d.mean())



16
Index:  15
1
Index:  0
136
8.5


In [36]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr_2d)
arr_2d_copy = np.random.randint(1,9,size=(4,4),dtype=int)
print(arr_2d_copy)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[4 4 4 1]
 [4 8 1 8]
 [7 2 2 8]
 [4 3 7 1]]


In [37]:
print(arr_2d)
print(arr_2d_copy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[4 4 4 1]
 [4 8 1 8]
 [7 2 2 8]
 [4 3 7 1]]


In [38]:
arr_2d > arr_2d_copy


array([[False, False, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
arr_2d < arr_2d_copy

array([[ True,  True,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
arr_2d == arr_2d_copy

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [50]:
print(arr_2d)
print(arr_2d_copy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[4 4 4 1]
 [4 8 1 8]
 [7 2 2 8]
 [4 3 7 1]]


In [51]:
print(np.logical_or(arr_2d,arr_2d_copy))
print(np.logical_and(arr_2d,arr_2d_copy))
print(np.logical_not(arr_2d,arr_2d_copy))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [52]:
import numpy as np
a=np.array(['a','f','s','r','w'])
b=np.array([1,2,4,5,7])

print(a)
print(b)


['a' 'f' 's' 'r' 'w']
[1 2 4 5 7]


In [3]:
print(b[b>4])

[5 7]


In [6]:
print(b[(b>2) & (b<5)])

[4]


In [7]:
a,b

(array(['a', 'f', 's', 'r', 'w'], dtype='<U1'), array([1, 2, 4, 5, 7]))

In [8]:
b[b>3] = 70
b

array([ 1,  2, 70, 70, 70])

In [12]:
print(np.where(b==70))

(array([2, 3, 4]),)


In [14]:
ind = np.where(b==70)
print(ind)
print(a[ind])


(array([2, 3, 4]),)
['s' 'r' 'w']


In [24]:
a=[1,2,0,0,4,0]
b=np.array(a)
print(b)
val = b[b>0]
print(val)
ind = np.where(b>0)
print("Index: ",ind)

[1 2 0 0 4 0]
[1 2 4]
Index:  (array([0, 1, 4]),)


In [26]:
a=[1,3,5,7,9,11,13,15,17,19]
b=np.array(a)
print(b)

print(b[b%3==0])

[ 1  3  5  7  9 11 13 15 17 19]
[ 3  9 15]


In [80]:
a=[1,2,3,4,5,6,7,8,9,10]
b=np.array(a)
print(b)
b[b%2==1] = -1
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [125]:
a=[11,2,13,4,15,6,27,8,19]
b=np.array(a)
max = b.max()
print(max)
ind=np.where(b==max)
print(ind)
b[b[:]==max]=0
print(b)

27
(array([6]),)
[11  2 13  4 15  6  0  8 19]


In [56]:
a=np.random.randint(1,30,size=(5,6))
a

array([[11,  2, 11,  7,  6,  8],
       [23,  2, 12,  2, 29, 19],
       [16, 12, 23,  6, 21, 13],
       [ 4, 28, 22, 16, 12, 25],
       [ 8,  8,  2,  3, 12, 15]])

In [58]:
bool_arr = a>20
print(bool_arr)

[[False False False False False False]
 [ True False False False  True False]
 [False False  True False  True False]
 [False  True  True False False  True]
 [False False False False False False]]


In [59]:
ans =  a[bool_arr]
print(ans)

[23 29 23 21 28 22 25]


In [60]:
b=a
print(b)

[[11  2 11  7  6  8]
 [23  2 12  2 29 19]
 [16 12 23  6 21 13]
 [ 4 28 22 16 12 25]
 [ 8  8  2  3 12 15]]


In [61]:
b[bool_arr] = 100
b

array([[ 11,   2,  11,   7,   6,   8],
       [100,   2,  12,   2, 100,  19],
       [ 16,  12, 100,   6, 100,  13],
       [  4, 100, 100,  16,  12, 100],
       [  8,   8,   2,   3,  12,  15]])

In [66]:
t_bool = b[:,2] == 100
print(t_bool)


[False False  True  True False]


In [67]:
b[t_bool,2] = 99
b

array([[ 11,   2,  11,   7,   6,   8],
       [100,   2,  12,   2, 100,  19],
       [ 16,  12,  99,   6, 100,  13],
       [  4, 100,  99,  16,  12, 100],
       [  8,   8,   2,   3,  12,  15]])

In [7]:
import numpy as np

a = np.random.randint(1,30,size=(4,5),dtype=int)
print(a)

[[25  5 28 19 23]
 [27 27 23  4  1]
 [12 12 29 25  4]
 [ 3 25 22 15 29]]


# Broadcasting

In [13]:
import numpy as np

a = np.random.randint(1,30,size=(4,5),dtype=int)
b = np.random.randint(1,30,size=(4,5),dtype=int)
print(a)
print(b)

[[15  5 19 15 16]
 [12  7 17 11  2]
 [23  6 24 22 22]
 [29 29 13 26 27]]
[[28  6 24 16 15]
 [29 28 16 23 15]
 [25 27  4 15 25]
 [17 23 18 15 22]]


In [14]:
ans = a-b
print(ans)

[[-13  -1  -5  -1   1]
 [-17 -21   1 -12 -13]
 [ -2 -21  20   7  -3]
 [ 12   6  -5  11   5]]


In [11]:
a = np.random.randint(1,30,size=(4,4),dtype=int)
b = np.random.randint(1,30,size=(4),dtype=int)
print(a)
print(b)

[[ 4 11 24 24]
 [ 4 11 11 12]
 [28  2 13 29]
 [ 2 14  2 28]]
[2 8 8 6]


In [12]:
ans = a-b
print(ans)

[[ 2  3 16 18]
 [ 2  3  3  6]
 [26 -6  5 23]
 [ 0  6 -6 22]]


In [21]:
a = np.random.randint(1,30,size=(4,2),dtype=int)
b = np.random.randint(1,30,size=(2,4),dtype=int)
print(a)
print(b)

[[13  6]
 [18  6]
 [20 13]
 [23 20]]
[[12 19 14 11]
 [21 24 11 15]]


In [16]:
ans=a-b
print(ans)

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [22]:
print(a)
print(b)
a=np.transpose(a)
print(a)
ans = a - b
print(ans)

[[13  6]
 [18  6]
 [20 13]
 [23 20]]
[[12 19 14 11]
 [21 24 11 15]]
[[13 18 20 23]
 [ 6  6 13 20]]
[[  1  -1   6  12]
 [-15 -18   2   5]]


In [33]:
import numpy as np
import csv

with open('year2017.csv', 'r') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace=True)
    file_list = list(file_data)

killed = []
wounded = []
country = []

for row in file_list:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed == ''] = '0.0'

np_wounded = np.array(wounded)
np_wounded[np_wounded == ''] = '0.0'

np_killed = np.array(np_killed, dtype=float)
np_wounded = np.array(np_wounded, dtype=float)

killed_wounded = np_killed + np_wounded

np_country = np.array(country)

bool_arr = np_country == 'India'
ans = killed_wounded[bool_arr]

print(int(sum(ans)))
print(int(sum(killed_wounded)))


1167
51372


In [2]:
import numpy as np
import csv

with open('year2017.csv') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace=True)
    file_list = list(file_data)

days = []
for i in file_list:
    days.append(i['Day'])

np_days = np.array(days, dtype=float)

s = np_days[(np_days>=10) & (np_days<=20)]
print(sum(s))
print(sum(np_days))

60345.0
174519.0


In [3]:
import numpy as np
import csv

with open('year2017.csv') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace=True)
    file_list = list(file_data)


month=[]
for i in file_list:
    month.append(i['Month'])

np_month = np.array(days,dtype=float)

month = np_days[(np_days>=1) ]


array([ 2.,  3.,  1., ..., 31., 31., 31.])